version: "2"
run:
  timeout: 10m
linters:
  enable:
    - testifylint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    testifylint:
      disable-all: true
      enable:
        - require-error
        - useless-assert
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
