apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  service: buildkite

bases:
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

# These patches are required for the metrics server to work with kind.
# They should not be applied on a real production deployment.
# patchesJson6902:
  # - target:
      # version: v1
      # kind: Deployment
      # name: metrics-server
      # namespace: kube-system
    # patch: |-
      # - op: add
        # path: /spec/template/spec/containers/0/args/-
        # value: --kubelet-insecure-tls
      # - op: add
        # path: /spec/template/spec/containers/0/args/-
        # value: --kubelet-preferred-address-types=InternalIP
