// Code generated by MockGen. DO NOT EDIT.
// Source: ../monitor/monitor.go

// Package scheduler_test is a generated GoMock package.
package scheduler_test

import (
	context "context"
	reflect "reflect"

	api "github.com/buildkite/agent-stack-k8s/v2/api"
	gomock "github.com/golang/mock/gomock"
)

// MockJobHandler is a mock of JobHandler interface.
type MockJobHandler struct {
	ctrl     *gomock.Controller
	recorder *MockJobHandlerMockRecorder
}

// MockJobHandlerMockRecorder is the mock recorder for MockJobHandler.
type MockJobHandlerMockRecorder struct {
	mock *MockJobHandler
}

// NewMockJobHandler creates a new mock instance.
func NewMockJobHandler(ctrl *gomock.Controller) *MockJobHandler {
	mock := &MockJobHandler{ctrl: ctrl}
	mock.recorder = &MockJobHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobHandler) EXPECT() *MockJobHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJobHandler) Create(arg0 context.Context, arg1 *api.CommandJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobHandlerMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobHandler)(nil).Create), arg0, arg1)
}

// MockjobResp is a mock of jobResp interface.
type MockjobResp struct {
	ctrl     *gomock.Controller
	recorder *MockjobRespMockRecorder
}

// MockjobRespMockRecorder is the mock recorder for MockjobResp.
type MockjobRespMockRecorder struct {
	mock *MockjobResp
}

// NewMockjobResp creates a new mock instance.
func NewMockjobResp(ctrl *gomock.Controller) *MockjobResp {
	mock := &MockjobResp{ctrl: ctrl}
	mock.recorder = &MockjobRespMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjobResp) EXPECT() *MockjobRespMockRecorder {
	return m.recorder
}

// CommandJobs mocks base method.
func (m *MockjobResp) CommandJobs() []*api.JobJobTypeCommand {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandJobs")
	ret0, _ := ret[0].([]*api.JobJobTypeCommand)
	return ret0
}

// CommandJobs indicates an expected call of CommandJobs.
func (mr *MockjobRespMockRecorder) CommandJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandJobs", reflect.TypeOf((*MockjobResp)(nil).CommandJobs))
}

// OrganizationExists mocks base method.
func (m *MockjobResp) OrganizationExists() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationExists")
	ret0, _ := ret[0].(bool)
	return ret0
}

// OrganizationExists indicates an expected call of OrganizationExists.
func (mr *MockjobRespMockRecorder) OrganizationExists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationExists", reflect.TypeOf((*MockjobResp)(nil).OrganizationExists))
}
