caches:
  - name: go_build
    cache_key:
      - agent: os
      - {agent: arch, fallbackLimit: true}
      - checksum: go.sum
      - env: BENCH_NONCE
    target_paths:
      - /root/.cache/go-build
  - name: go_mod
    cache_key:
      - agent: os
      - {agent: arch, fallbackLimit: true}
      - checksum: go.sum
      - env: BENCH_NONCE
    target_paths:
      - /root/.cache/go-mod
  - name: golangci_lint
    cache_key:
      - agent: os
      - {agent: arch, fallbackLimit: true}
      - checksum: .golangci.yaml
      - env: BENCH_NONCE
    target_paths:
      - /root/.cache/golangci-lint
