# This file is manually deployed to our cluster.
---
apiVersion: v1
kind: PodTemplate
metadata:
  name: go-with-cache
  namespace: buildkite
template:
  spec:
    containers:
      - name: container-0
        image: public.ecr.aws/docker/library/golang:1.26.4-alpine@sha256:f1ddd9fe14fffc091dd98cb4bfa999f32c5fc77d2f2305ea9f0e2595c5437c14
        # These golang related cache uses node local storage.
        # We will soon refactor this to use the incoming Buildkite Cache.
        env:
          - name: GOCACHE
            value: /var/cache/go-build
          - name: GOMODCACHE
            value: /var/cache/go-mod
          - name: GOLANGCI_LINT_CACHE
            value: /var/cache/golangci-lint
        volumeMounts:
          - name: go-build
            mountPath: /var/cache/go-build
          - name: go-mod
            mountPath: /var/cache/go-mod
          - name: golangci-lint-cache
            mountPath: /var/cache/golangci-lint
    volumes:
      - name: go-build
        hostPath:
          path: /var/cache/buildkite/agent-stack-k8s-ci/go-build
          type: DirectoryOrCreate
      - name: go-mod
        hostPath:
          path: /var/cache/buildkite/agent-stack-k8s-ci/go-mod
          type: DirectoryOrCreate
      - name: golangci-lint-cache
        hostPath:
          path: /var/cache/buildkite/agent-stack-k8s-ci/golangci-lint
          type: DirectoryOrCreate
