failure-spec: &failure-spec
  restartPolicy: OnFailure
  containers:
    - name: ${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_STEP_ID}-failure
      image: deftinc/failwhale
      command: ["/app/entrypoint.sh"]
      resources:
        requests:
          cpu: "0.25"
          memory: "250Mi"
        limits:
          cpu: "0.25"
          memory: "250Mi"

success-spec: &success-spec
  restartPolicy: OnFailure
  containers:
    - name: ${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_STEP_ID}-success
      image: deftinc/winpenguin
      command: ["/app/entrypoint.sh"]
      resources:
        requests:
          cpu: "0.25"
          memory: "250Mi"
        limits:
          cpu: "0.25"
          memory: "250Mi"

echo-spec: &source-spec
  restartPolicy: OnFailure
  containers:
    - name: ${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_STEP_ID}-source
      image: deftinc/lawyer_lion
      command: ["/app/entrypoint.sh"]
      resources:
        requests:
          cpu: "0.25"
          memory: "250Mi"
        limits:
          cpu: "0.25"
          memory: "250Mi"

steps:
  - label: "Consulting my :crystal_ball: thats inside my :k8s: pod"
    env:
      BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"
    plugins:
      - k8s-job#phw-add-code-mount:
          pod-spec: *source-spec
