steps:
  - label: ":lint-roller: lint"
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: golang:alpine
                command: [.buildkite/steps/lint.sh]
                env:
                - name: CONFIG
                  value: /etc/config.yaml
                envFrom:
                  - secretRef:
                      name: agent-stack-k8s-secrets
                volumeMounts:
                - mountPath: /etc/config.yaml
                  name: agent-stack-k8s-config
                  subPath: config.yaml

  - label: ":buildkite: integration tests"
    agents:
      queue: kubernetes
    artifact_paths: junit-*.xml
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: integration-tests
            volumes:
            - name: agent-stack-k8s-config
              configMap:
                name: agent-stack-k8s-config
            containers:
              - image: golang:latest
                command: [.buildkite/steps/tests.sh]
                env:
                - name: CONFIG
                  value: /etc/config.yaml
                envFrom:
                  - secretRef:
                      name: agent-stack-k8s-secrets
                volumeMounts:
                - mountPath: /etc/config.yaml
                  name: agent-stack-k8s-config
                  subPath: config.yaml
