apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integration-tests
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integration-tests
  namespace: buildkite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: integration-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: integration-tests
subjects:
- kind: ServiceAccount
  name: integration-tests
  namespace: buildkite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: docker
  namespace: buildkite
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker
  namespace: buildkite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: docker
  namespace: buildkite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: docker
subjects:
- kind: ServiceAccount
  name: docker
  namespace: buildkite
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy
  namespace: buildkite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy
  namespace: buildkite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: deploy
  namespace: buildkite
---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
 metadata:
   name: read-release-secret
   namespace: buildkite
 rules:
 - apiGroups: [""]
   resources: ["secrets"]
   resourceNames: ["release-secrets"]
   verbs: ["get", "watch", "list"]
---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: RoleBinding
 metadata:
   name: read-release-secret
   namespace: buildkite
 subjects:
 - kind: ServiceAccount
   name: release
   namespace: buildkite
 roleRef:
   kind: Role
   name: read-release-secret
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release
  namespace: buildkite
