apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: buildkite
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: agent-k8s-job
      containers:
        - name: buildkiteagent
          image: buildkite/agent:edge-alpine-k8s
          # imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: BUILDKITE_AGENT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: BUILDKITE_AGENT_CONFIG
              value: "/buildkite/config/buildkite-agent.cfg"
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite-agent-token
                  key: token
                  optional: false
          volumeMounts:
            - name: builds
              mountPath: "/buildkite/builds"
            - name: config
              mountPath: "/buildkite/config"
              readOnly: true
            - name: hooks
              mountPath: "/buildkite/hooks"
              readOnly: true
            - name: secrets
              mountPath: "/buildkite/secrets"
              readOnly: true
        - name: dind-daemon
          image: docker:dind
          # imagePullPolicy: IfNotPresent
          command: ["dockerd", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2375"]
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "2"
              memory: "10Gi"
            limits:
              cpu: "2"
              memory: "14Gi"
          volumeMounts:
            - name: builds
              mountPath: /buildkite/builds
            - name: docker-graph-storage
              mountPath: /var/lib/docker
      terminationGracePeriodSeconds: 900
      volumes:
        - name: config
          configMap:
            name: agent-config
            items:
              - key: "buildkite-agent.cfg"
                path: "buildkite-agent.cfg"
        - name: hooks
          configMap:
            name: agent-hooks
            items:
              - key: "environment"
                path: "environment"
              - key: "pre-exit"
                path: "pre-exit"
        - name: secrets
          secret:
            secretName: buildkite-secrets
            defaultMode: 0600
            optional: true
        - name: builds
          emptyDir: {}
        - name: docker-graph-storage
          emptyDir: {}
