apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-scale-up
  namespace: buildkite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent
  minReplicas: 3
  maxReplicas: 90
  metrics:
    - type: External
      external:
        metric:
          name: buildkite_scheduled_jobs_count
          selector:
            matchLabels:
              queue: default
        target:
          type: Value
          value: 1
  behavior:
    scaleDown:
      selectPolicy: Disabled
    scaleUp:
      stabilizationWindowSeconds: 30
      selectPolicy: Max
      policies:
        - type: Pods
          value: 100
          periodSeconds: 30
        - type: Percent
          value: 100
          periodSeconds: 30
