apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-deployer-scale-down
  namespace: buildkite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-deployer
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: External
      external:
        metric:
          name: buildkite_busy_agent_percentage
          selector:
            matchLabels:
              queue: deployer
        target:
          type: Value
          value: 99
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
      selectPolicy: Max
      policies:
        - type: Pods
          value: 40
          periodSeconds: 10
    scaleUp:
      selectPolicy: Disabled
