blank_issues_enabled: true
contact_links:
  - name: agent-stack-k8s Documentation
    url: https://github.com/buildkite/agent-stack-k8s/blob/main/README.md
    about: Check the documentation before opening an issue
  - name: Buildkite Support
    url: https://buildkite.com/support
    about: Ask questions not specifically related to the Agent K8s Stack.
  - name: Buildkite Community
    url: https://forum.buildkite.community
    about: Ask and answer questions with other Buildkite and Agent K8s Stack users.
