agentToken: ""

agentStackSecret: ""

nodeSelector: {}
tolerations: []

config:
  prometheus-port: 9216
  reservation-expiry-seconds: 900
  enable-completion-watcher: true
  pod-pending-timeout: 15m

resources:
  requests:
    cpu: 100m
    memory: 100Mi

labels: {}

annotations: {}

secretsMetadata: {}

serviceAccountMetadata: {}

monitoring:
  deployGrafanaDashboard: false
  podMonitor:
    deploy: false
