# A sample https://github.com/buildkite/docker-ssh-env-config secret
# kubectl create secret generic agent-stack-k8s --from-file=SSH_PRIVATE_RSA_KEY="$HOME/.ssh/id_rsa"
apiVersion: v1
kind: Secret
metadata:
  name: agent-stack-k8s
data:
  SSH_PRIVATE_RSA_KEY: <your base64 encoded git ssh private key here>
